services:
  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: solaceassignment
    volumes:
      - psql18:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  psql18: